apiVersion: v1
kind: Service
metadata:
  name: example
  labels:
    app: example
spec:
  type: LoadBalancer
  selector:
    app: example
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP